name: Daily Data Update

on:
  # schedule:
  #   # - cron: "0 1 * * *"
  #   - cron: "* * * * *"
  push:
    branches: main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: |
          pwd
          curl -o data/jalali_all.min-new.json https://github.com/SamadiPour/rial-exchange-rates-archive/releases/latest/download/jalali_all.min.json

      - name: Replace existing file
        run: |
          cd data
          rm jalali_all.min.json
          mv jalali_all.min-new.json jalali_all.min.json
